dat<-read.table("household_power_consumption.txt",header = TRUE, sep=';')


dat$DateTime <- strptime(paste(dat$Date, dat$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
data<-subset(dat,dat$Date=="1/2/2007" | dat$Date=="2/2/2007")
data$Global_active_power<-as.numeric(data$Global_active_power)
data$Voltage<-as.numeric(data$Voltage)
data$Sub_metering_1<-as.numeric(data$Sub_metering_1)
data$Sub_metering_2<-as.numeric(data$Sub_metering_2)
data$Sub_metering_3<-as.numeric(data$Sub_metering_3)

png("plot4.png",width = 480, height = 480)
par(mfrow=c(2,2))
with(data, plot(DateTime, Global_active_power, type="l", xlab="", ylab="Global Active Power"))
with(data, plot(DateTime, Voltage, type = "l", xlab="datetime", ylab="Voltage"))
with(data, plot(DateTime, Sub_metering_1, type="l", xlab="", ylab="Energy sub metering"))
with(data,lines(DateTime, Sub_metering_2,type="l", col= "red"))
with(data,lines(DateTime, Sub_metering_3,type="l", col= "blue"))
legend(c("topright"), c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty= 1, lwd=2, col = c("black", "red", "blue"))
with(data, plot(DateTime, Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power"))
dev.off()
